[package]
name = "uhal-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.121"

[build-dependencies]
bindgen = "0.69.4"
num_cpus = "1.16.0"

